# Generated by Django 3.2.5 on 2021-08-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.png', upload_to='teacher')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('speciality', models.CharField(choices=[('English', 'English Teacher'), ('Scratch', 'Scratch Teacher'), ('Science', 'Science Teacher'), ('Sport', 'Sport Teacher')], max_length=50)),
            ],
        ),
    ]
